name: Optimize PNGs
on:
  push:
    branches:
      - main
      - testing
    paths:
      - '**.png'

jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          api-key: ${{ secrets.CRUSH_API_KEY }}
      - name: Crush images
        uses: crush-pics/crush-pics-github-action@master